# 配置 Spring Boot 应用端口号
server:
  port: 8091

spring:
  profiles:
    active: dev

#person:
#  lastName: zhangsan
#  age: 18
#  boss: false
#  birth: 2017/12/12
#  maps: {k1: v1, k2: 12}
#  lists:
#    - lisi
#    - zhaoliu
#  dog:
#    name: 小狗
#    age: 2

---
spring:
  profiles: dev

server:
  port: 8083
---
spring:
  profiles: prod

server:
  port: 8084